#!/usr/bin/env rake

begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

begin
  require 'rdoc/task'
rescue LoadError
  require 'rdoc/rdoc'
  require 'rake/rdoctask'
  RDoc::Task = Rake::RDocTask
end

RDoc::Task.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'IndexedSearch'
  rdoc.options << '--line-numbers'
  rdoc.rdoc_files.include('README.rdoc')
  rdoc.rdoc_files.include('app/**/*.rb')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

Bundler::GemHelper.install_tasks

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec) do |t|
  t.verbose = true
end
task :default  => :spec

desc 'Analyze code coverage with tests and show a report'
task :coverage => ['coverage:clobber', 'coverage:run', 'coverage:open']
namespace :coverage do
  desc 'Remove any previous output generated by simplecov'
  task :clobber do
    FileUtils.rm_rf(File.expand_path('../coverage', __FILE__))
  end
  desc 'Generate simplecov report'
  task :run do
    ENV['USE_SIMPLECOV'] = :true.to_s
    Rake::Task['spec'].invoke
    # see top of test helper for the rest of this task, which is triggered with the environment var....
  end
  desc 'Open simplecov report in default browser'
  task :open do
    require 'launchy'
    Launchy.open(File.expand_path('../coverage/index.html', __FILE__))
  end
end
